# Object Repository file - used to store the locator in this file
# Store data in key-value player

# Signup page locators
signUpPage = //a[@class='ico-register']
firstName = //input[@name='FirstName']
lastName = //input[@name='LastName']
email = //input[@name='Email']
male = //input[@id='gender-male']
female = //input[@id='gender-female']
newsLetter = //input[@id='NewsLetterSubscriptions_0__IsActive']
password = //input[@id='Password']
confirmPassword = //input[@id='ConfirmPassword']
registerbtn = //button[@id='register-button']

# login page locators
loginPage = //a[@class='ico-login']
loginEmail = //input[@id='Email']
loginPassword = //input[@id='Password']
loginBtn = //button[@class='button-1 login-button']