browser_name = edge

#Dev Environment Details
app_devurl= www.demo.nopcommerce.com
app_devUserName = achulshing.jamadar@gmail.com
app_devPassword = Dhondi@123

#QA Environment Details
app_qaurl= https://demo.nopcommerce.com/
app_qaUserName = achulshing.jamadar@gmail.com
app_qaPassword = Dhondi@123